### ISSUE TITLE
No such file or directory: '/xxx/avatarrex_zzr/merged.pkl

### ISSUE THREAD

**Issue by ZhenyanSun** [shad0wta9/meshavatar#8]
Dear author，
Where can I find the merged.pkl? how to produce it?

**Comment by shad0wta9** [comment]
It's a bug and I have fixed it.
Try `git pull` and run it again!

**Comment by ZhenyanSun** [comment]
> It's a bug and I have fixed it. Try `git pull` and run it again!

thx

**Comment by azureovo** [comment]
> It's a bug and I have fixed it. Try `git pull` and run it again!

hi Dear author，why i still encounter this problem？
![Uploading cd5f96f58d74f0937998c26df63f8c7c.png…]()

**Comment by azureovo** [comment]
> It's a bug and I have fixed it. Try `git pull` and run it again!

hi Dear author，why i still encounter this problem？
<img width="652" alt="cd5f96f58d74f0937998c26df63f8c7c" src="https://github.com/user-attachments/assets/55e438c4-6c7a-41cd-9c84-af257ccf6ada">

**Comment by shad0wta9** [comment]
You should check you have use the dataset class correctly here. (For AvatarReX, DatasetSMPL should be loaded)
https://github.com/shad0wta9/meshavatar/blob/8e3e9140f2caec0bd5c39b52e2c465515c2b1aa4/train.py#L418-L424

**Comment by shad0wta9** [comment]
sry it's the same bug in the preprocessing code. I have fixed it. Try `git pull` and run it again!

**Comment by azureovo** [comment]
> sry it's the same bug in the preprocessing code. I have fixed it. Try `git pull` and run it again!

Oh, thank you so much. During this period, I found that when I was running `sh 0 configs/avatarrex_zzr.json`, I couldn't find the `dataset_train`, which confused me for a long time. I look forward to your modification.
<img width="540" alt="cf858aa29db1f52f556b65e9ee955728" src="https://github.com/user-attachments/assets/29443cdf-8c38-46d4-95a2-1a111be672f1">

**Comment by azureovo** [comment]
> sry it's the same bug in the preprocessing code. I have fixed it. Try `git pull` and run it again!
The complete question is:
`/root/miniconda3/envs/meshavatar/lib/python3.9/site-packages/torch/functional.
py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2894.)
return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
tetrahedral grid ranges from [-1.000000 -1.400000 -0.250001] to [1.000000 0.600000 0.250000]
Cuda path /root/miniconda3/envs/meshavatar
End of OptiXStateWrapper 
Encoder output: 32 dims
Traceback (most recent call last):
File "/root/meshavatar/train.py", line 469, in <module>
geometry, mat = optimize_mesh(glctx, geometry, mat, lgt, dataset_train, dataset_validate,
NameError: name 'dataset_train' is not defined
OptiXStateWrapper destructor `

**Comment by shad0wta9** [comment]
Is there `calibration_full.json` in the data directory?

**Comment by azureovo** [comment]
> Is there `calibration_full.json` in the data directory?

yes
<img width="237" alt="f44e668d5cf70f4ecb9d258d865751cd" src="https://github.com/user-attachments/assets/dc203fb6-2d59-4c8f-8e03-75e4cb666eef">

**Comment by shad0wta9** [comment]
You can debug the following lines? The definition of `dataset_train` will be skipped only when `calibration_full.json` not exists.
https://github.com/shad0wta9/meshavatar/blob/1e92652446d3d54861549b170f094bf788dfef36/train.py#L418-L426

**Comment by azureovo** [comment]
> You can debug the following lines? The definition of `dataset_train` will be skipped only when `calibration_full.json` not exists.
> 
> https://github.com/shad0wta9/meshavatar/blob/1e92652446d3d54861549b170f094bf788dfef36/train.py#L418-L426

well now i cannot find `cam_ssns.txt`，how can i solve this problem
<img width="495" alt="{7F5AF2E3-D98D-435a-8CC8-6D339B08261E}" src="https://github.com/user-attachments/assets/fa86e5a1-d05a-4fc1-afd2-9676bc264de5">

**Comment by shad0wta9** [comment]
`cam_ssns.txt` is the file that records all the camera names. It seems that this file was not released with the dataset.
You can create it simply by the following lines. I will fix it later.
```python
cam_data = get_cams(data_dir)
open(os.path.join(data_dir, "cam_ssns.txt"), "w").write('\n'.join(sorted(list(cam_data.keys()))))
```
`get_cams` is the same function used in `dataset/dataset_smpl.py`.
